services:

  # === METRICS ===

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # === EVENT BROKER ===

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.9.4
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
      anamnesi-pregressa-mongo-db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # === ANAMNESI PREGRESSA ===

  anamnesi-pregressa:
    build:
      context: .
      dockerfile: anamnesi_pregressa/Dockerfile
    container_name: anamnesi-pregressa
    #    environment:
    #      - LOG_LEVEL=debug
    #      - LOG_ADD_SOURCE=true
    environment:
      - CONFIG_SERVER_HOST_NAME=anamnesi-pregressa-mongo-db
      - CONFIG_SERVER_PORT=27017
      - CONFIG_SERVER_DB_NAME=anamnesi-pregressa-mongo-db
      - CONFIG_SERVER_DB_USERNAME=root
      - CONFIG_SERVER_DB_PASSWORD=password
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - app-network
    #    healthcheck:
    #      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
    #      interval: 5s
    #      timeout: 3s
    #      retries: 3
    #      start_period: 10s
    depends_on:
      prometheus:
        condition: service_healthy
      anamnesi-pregressa-mongo-db:
        condition: service_started
      kafka:
        condition: service_healthy

  anamnesi-pregressa-mongo-db:
    image: mongo:latest
    container_name: anamnesi-pregressa-mongo-db
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    #      - MONGO_INITDB_DATABASE=anamnesi-pregressa-mongo-db
    volumes:
      - anamnesi-pregressa-mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # === DIARIO CLINICO ===

  diario-clinico:
    build:
      context: .
      dockerfile: diario_clinico/Dockerfile
    container_name: diario-clinico
    #    environment:
    #      - LOG_LEVEL=debug
    #      - LOG_ADD_SOURCE=true
    environment:
      - CONFIG_SERVER_HOST_NAME=diario-clinico-mongo-db
      - CONFIG_SERVER_PORT=27017
      - CONFIG_SERVER_DB_NAME=diario-clinico-mongo-db
      - CONFIG_SERVER_DB_USERNAME=root
      - CONFIG_SERVER_DB_PASSWORD=password
    networks:
      - app-network
    #    healthcheck:
    #      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
    #      interval: 5s
    #      timeout: 3s
    #      retries: 3
    #      start_period: 10s
    depends_on:
      prometheus:
        condition: service_healthy
      diario-clinico-mongo-db:
        condition: service_started
      kafka:
        condition: service_healthy

  diario-clinico-mongo-db:
    image: mongo:latest
    container_name: diario-clinico-mongo-db
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    #      - MONGO_INITDB_DATABASE=diario-clinico-mongo-db
    volumes:
      - diario-clinico-mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # === TERAPIA ===

  terapia:
    build:
      context: .
      dockerfile: terapia/Dockerfile
    container_name: terapia
    #    environment:
    #      - LOG_LEVEL=debug
    #      - LOG_ADD_SOURCE=true
    environment:
      - CONFIG_SERVER_HOST_NAME=terapia-mongo-db
      - CONFIG_SERVER_PORT=27017
      - CONFIG_SERVER_DB_NAME=terapia-mongo-db
      - CONFIG_SERVER_DB_USERNAME=root
      - CONFIG_SERVER_DB_PASSWORD=password
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - app-network
    #    healthcheck:
    #      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
    #      interval: 5s
    #      timeout: 3s
    #      retries: 3
    #      start_period: 10s
    depends_on:
      prometheus:
        condition: service_healthy
      terapia-mongo-db:
        condition: service_started
      kafka:
        condition: service_healthy

  terapia-mongo-db:
    image: mongo:latest
    container_name: terapia-mongo-db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    #      - MONGO_INITDB_DATABASE=terapia-mongo-db
    volumes:
      - terapia-mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # === SERVICE ===

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    container_name: service
    #    environment:
    #      - LOG_LEVEL=debug
    #      - LOG_ADD_SOURCE=true
    environment:
      - CONFIG_SERVER_HOST_NAME=service-mongo-db
      - CONFIG_SERVER_PORT=27017
      - CONFIG_SERVER_DB_NAME=service-mongo-db
      - CONFIG_SERVER_DB_USERNAME=root
      - CONFIG_SERVER_DB_PASSWORD=password
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - app-network
    #    healthcheck:
    #      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
    #      interval: 5s
    #      timeout: 3s
    #      retries: 3
    #      start_period: 10s
    depends_on:
      prometheus:
        condition: service_healthy
      service-mongo-db:
        condition: service_started
      kafka:
        condition: service_healthy

  service-mongo-db:
    image: mongo:latest
    container_name: service-mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    #      - MONGO_INITDB_DATABASE=service-mongo-db
    volumes:
      - service-mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # === API-GATEWAY ===

  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: api_gateway
    #    environment:
    #      - LOG_LEVEL=debug
    #      - LOG_ADD_SOURCE=true
    ports:
      - "8080:8080"
    networks:
      - app-network
#    depends_on:
#      service:
#        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
  service-mongo-data:
  terapia-mongo-data:
  diario-clinico-mongo-data:
  anamnesi-pregressa-mongo-data: